-- MySQL Script generated by MySQL Workbench
-- Sat Jun 14 23:18:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema farmlogbook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `farmlogbook` ;

-- -----------------------------------------------------
-- Schema farmlogbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmlogbook` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `farmlogbook` ;

-- -----------------------------------------------------
-- Table `farmlogbook`.`crop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmlogbook`.`crop` ;

CREATE TABLE IF NOT EXISTS `farmlogbook`.`crop` (
  `CropID` INT NOT NULL AUTO_INCREMENT,
  `CropName` VARCHAR(50) NULL DEFAULT NULL,
  `CropType` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CropID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmlogbook`.`farm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmlogbook`.`farm` ;

CREATE TABLE IF NOT EXISTS `farmlogbook`.`farm` (
  `FarmID` INT NOT NULL AUTO_INCREMENT,
  `FarmerName` VARCHAR(100) NULL DEFAULT NULL,
  `Location` VARCHAR(100) NULL DEFAULT NULL,
  `SizeInAcres` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`FarmID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmlogbook`.`harvestsale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmlogbook`.`harvestsale` ;

CREATE TABLE IF NOT EXISTS `farmlogbook`.`harvestsale` (
  `HarvestID` INT NOT NULL AUTO_INCREMENT,
  `PlantingID` INT NULL DEFAULT NULL,
  `HarvestDate` DATE NULL DEFAULT NULL,
  `QuantityHarvested` DECIMAL(10,2) NULL DEFAULT NULL,
  `SaleAmount` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`HarvestID`),
  INDEX `PlantingID` (`PlantingID` ASC) VISIBLE,
  CONSTRAINT `harvestsale_ibfk_1`
    FOREIGN KEY (`PlantingID`)
    REFERENCES `farmlogbook`.`planting` (`PlantingID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmlogbook`.`input`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmlogbook`.`input` ;

CREATE TABLE IF NOT EXISTS `farmlogbook`.`input` (
  `InputID` INT NOT NULL AUTO_INCREMENT,
  `PlantingID` INT NULL DEFAULT NULL,
  `InputType` VARCHAR(50) NULL DEFAULT NULL,
  `Quantity` DECIMAL(10,2) NULL DEFAULT NULL,
  `Cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `DateApplied` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`InputID`),
  INDEX `PlantingID` (`PlantingID` ASC) VISIBLE,
  CONSTRAINT `input_ibfk_1`
    FOREIGN KEY (`PlantingID`)
    REFERENCES `farmlogbook`.`planting` (`PlantingID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmlogbook`.`planting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmlogbook`.`planting` ;

CREATE TABLE IF NOT EXISTS `farmlogbook`.`planting` (
  `PlantingID` INT NOT NULL AUTO_INCREMENT,
  `FarmID` INT NULL DEFAULT NULL,
  `CropID` INT NULL DEFAULT NULL,
  `PlantingDate` DATE NULL DEFAULT NULL,
  `ExpectedHarvestDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`PlantingID`),
  INDEX `FarmID` (`FarmID` ASC) VISIBLE,
  INDEX `CropID` (`CropID` ASC) VISIBLE,
  CONSTRAINT `planting_ibfk_1`
    FOREIGN KEY (`FarmID`)
    REFERENCES `farmlogbook`.`farm` (`FarmID`),
  CONSTRAINT `planting_ibfk_2`
    FOREIGN KEY (`CropID`)
    REFERENCES `farmlogbook`.`crop` (`CropID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
